### ISSUE TITLE
Playback Failed

### ISSUE THREAD

**Issue by eracknaphobia** [d21spike/plugin.video.sling#10]
Looks like the license key is getting 403'd again

**Comment by d21spike** [comment]
I think it may be issues on Sling's end, just had multiple attempts to play a movie through the browser and each time it failed on widevine
![image](https://user-images.githubusercontent.com/6399602/72805499-04c79f00-3c21-11ea-8614-708a7a1b7aa3.png)

**Comment by d21spike** [comment]
As of right now, commit 59511010c6ef366771efc3c2860e8365f8d826b7, version 0.082 has playback functional. The browser based Sling still seems to be a hit or miss. Time will tell if they're just having issues or if changes are coming.
