### ISSUE TITLE
Not all channels are showing in the guide

### ISSUE THREAD

**Issue by clonesr1** [d21spike/plugin.video.sling#12]
As I was getting guide setup, I noticed the ESPN, MLB network, and NBC sports Network, (and I 
(https://github.com/d21spike/plugin.video.sling/files/4128106/Log_1_28_20_sling.tx.txt)
believe Sy FY channel) are missing from the guide, even though when I click to update channels manually, it appears those channels are updated as well. I have 'cleared data in general/guide in the pvr settings as well, but the channel are not showing. 

I did go into the sling addon, and the channels are listed there, and then looked in the sling.epg.xml file and those channels are missing in there.  

I can add a log if needed but since it is not exactly an error, I was unsure.  I did cut/paste the sling.epg file here
[sling.epg.txt](https://github.com/d21spike/plugin.video.sling/files/4114890/sling.epg.txt)

I have installed the addon on another (win10) system and I am getting the same result. Those channels are missing in the epg.xml and the guide as well. ????

**Comment by d21spike** [comment]
Addressed in e964e6513cd64bcd2170b41974e4d51e7d76f131
