### ISSUE TITLE
Running Slinger service on remote machine

### ISSUE THREAD

**Issue by xags** [d21spike/plugin.video.sling#16]
I'd like to know if it would be possible to run the Slinger service on a remote non-kodi machine. I have six different clients in my home that are using this plugin and the VOD/channel/guide update process has to run on each of them. Since I only am concerned with the channel and guide data that gets generated, is it possible to break out just the slinger.py service?

**Comment by d21spike** [comment]
So the service depends on the add-on itself mainly for authorization portion of it. This takes care of the user subscriptions, regional info, and etc.

For it to be truly standalone all that would need incorporated. With hard-coded values it is possible to do, but at that point much simpler just to have a script on a cron job populating a db file. That said, there's no harm in installing the add-on and just not using it. Also keep in mind, any subscription changes will have to be manually updated if you hard-code.

**Comment by xags** [comment]
@d21spike thanks for the response! I was successfully able to fully move the Slinger service and allow it to dynamically update the values. 

My use case was to have the ability to run it on a regular Linux server so that my multiple endpoints talk to it instead of each of them updating their own database. 

It also fixes all of the oddities when integrating with iptv-simple and doesn't require reloads or the service or the case where it shows a blank guide (can also be fixed other ways but in a few weeks of use I have yet to have an issue). 

I have two separate issues I will open soon having to do with sound on premium channels and ISA/plugin not starting at the 'live' position that I have a really odd (not correct) workaround that I can't quite explain. 

Anyway, keep up the good work!

**Comment by d21spike** [comment]
@xags Yeah I've had it in a straight python script updating a DB with no issue. I've also had an instance where it was running on a remote hosting server in PHP. As long as Sling knows where the database is, all is well.

Within the scope of the add-on, I'm sure you can understand why such functionality is not possible given that it has to run on multiple devices and abide by Kodi rules.

If you're really ambitious. All you need to do is run a lamp server on your linux box and host two pages, one for the channels and one for the guide. That should keep your Kodi guide happy. I did this in my PHP version, in this case it was accessible wherever I was via internet.

**Comment by xags** [comment]
@d21spike, yep that's exactly what I'm doing. Very happy and totally understood the way it's built today will work for most people.
