### ISSUE TITLE
Sling fails to open after entering credentials

### ISSUE THREAD

**Issue by faptaincrunch** [d21spike/plugin.video.sling#21]
A couple of us have an issue where after installing the latest Sling zip from Github, Sling fails to load. After uninstalling and setting Sling to default, and logging in, Sling goes to local video screen and fails to open. Using Sling from Master. 

Kodi log https://paste.kodi.tv/juvexepiyu.kodi and log from another user with same issue https://paste.kodi.tv/exunolopec

**Comment by ilovegit1** [comment]
I am having the same issue. I downloaded the most recent master file from yesterday. After entering my credentials it takes me back to the local library directory. Log file entry:

ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.sling/
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.sling/) failed

Appreciate the help.

**Comment by eracknaphobia** [comment]
Currently being worked on https://github.com/d21spike/plugin.video.sling/issues/22#issuecomment-740131171

**Comment by d21spike** [comment]
@ilovegit1 make sure Debugging is turned on via Add-on settings (as well as debugging in Kodi settings)
![image](https://user-images.githubusercontent.com/6399602/101546687-2cc60b00-3977-11eb-9162-ed3ae2ae2721.png)
and
![image](https://user-images.githubusercontent.com/6399602/101546787-4ff0ba80-3977-11eb-9c2d-04a76601ebf4.png)

 Also, make sure you're on version 0.0.104 or above. Then post a log if still having issues, should have more information.

**Comment by ilovegit1** [comment]
Hello, 

As requested, see attached log.

[kodi.log](https://github.com/d21spike/plugin.video.sling/files/5663076/kodi.log)
![Etsy Tax Payer](https://user-images.githubusercontent.com/75700302/101564285-b8439a00-397f-11eb-9e8f-e0d4028fc492.JPG)

Please advise,
Thanks!

**Comment by d21spike** [comment]
Issue #22 is resolved, are you still having issues?

**Comment by bds3151** [comment]
No - working fine here.  Thanks


-----Original Message-----

**Comment by d21spike** [comment]
Sounds good!
