### ISSUE TITLE
delimiters not consistent with IPTV Merge

### ISSUE THREAD

**Issue by hagertyoh** [d21spike/plugin.video.sling#23]
Using this app with IPTV Merge to place the epg in iptv simple client. It appears Somewhere between the processing of the two apps in channel tag/category, simple tv is using a comma delimiter to separate multiple tags and iptv merge only recognizes semi colons.

**Comment by hagertyoh** [comment]
Disabling IPTV merge, i realized IPTV merge is not the problem so must need fixed in Sling addon

**Comment by d21spike** [comment]
@hagertyoh I'm assuming what you're referring to here is in the channels.m3u file, specifically the `group-title` tag associated with channels.

For example:
```java
#EXTINF:-1 tvg-id="be5a3bce259a4c13947f4b4fbae5e005" tvg-name="A&E" tvg-logo="http://p-img.movetv.com/cms/images/543dc859144fad30e6daa4ef2942a66f6d384af9.png" group-title="Sling TV; Entertainment, Movies",A&E
plugin://plugin.video.sling/?mode=play&url=http://cbd46b77.cdn.cms.movetv.com/cms/api/channels/be5a3bce259a4c13947f4b4fbae5e005/schedule/now/playback_info.qvt
```
Here we can pick out: `group-title="Sling TV; Entertainment, Movies"` and you'll notice this has "Sling TV" followed by a semicolon and then comma separated groups associated with that channel. What this does is designate a parent group for Kodi and then everything following becomes a subgroup. Essentially allowing you to isolate Sling TV channels.
![image](https://user-images.githubusercontent.com/6399602/102228683-f88fa480-3eb8-11eb-990a-8fd7f43c9cc6.png)

If we change this semicolon to a comma, in which case it's treated like another group, we get an undesired effect. See below.
![image](https://user-images.githubusercontent.com/6399602/102228573-dac23f80-3eb8-11eb-8cd2-33fec7b7ef21.png)

**Comment by hagertyoh** [comment]
@d21spike Yes that is the file location.   i think Make them all semicolons,  Using your example the comma between " Entertainment, Movies” needs to be a semicolon.  There are no sub groups in the PVR.  I am not proficient but it appears the "group-title=" sets the metadata  listing all the groups this channel, A&E, belongs.  When filtering,  A&E should show up in the Sling TV,  Entertainment, and Movies filters.   Currently it would show up in Sling TV filter and a new unique filter called "Entertainment, Movie".  it would not show up in the Entertainment or Movie filters.  This becomes more critical when i put it next to my TVHeadend Channels.

**Comment by d21spike** [comment]
@hagertyoh See commit d6fb712ef9aab348f3afc4a08cc6b03cb180022b

**Comment by hagertyoh** [comment]
@d21spike   thanks, i might not be explaining my thoughts very well but i think you will like the result.  Is there a way for me to test or are you good?  This is my very first time working on this forum.  

Unrelated to this topic, i saw issue reported on the kodi forum on the last widevine upgrade cause significant playback issues.

**Comment by d21spike** [comment]
@hagertyoh The changes are pushed so you can either clone this repo as a zip and install that via kodi or if you use my IO-Fault repo that has it pushed as well.

Yes live channels are currently experiencing issues.

**Comment by hagertyoh** [comment]
@d21spike  - thanks works great.
