### ISSUE TITLE
Audio on Premium Channels Not Working Consistently

### ISSUE THREAD

**Issue by xags** [d21spike/plugin.video.sling#24]
When using the addon, premium channels (EPIX, Showtime, Starz) frequently have missing audio when starting the channel. Sometimes going to a non-premium channel and switching back fixes the issue. While troubleshooting I've found the removing the following from sling.py allows consistent playback without audio issues for premium.

The code chunk that is causing the issue (~line 251):

```python      
     if xbmc.Player().isPlayingVideo() and len(xbmc.Player().getAvailableAudioStreams()) > 1:
            xbmc.Player().setAudioStream(0)
```
Commenting/removing this block is all that is needed for consistent playback.

I can create a PR but I'm not sure what the point of this code block is for or if there is a better way to fix this. Any input is welcome.

**Comment by d21spike** [comment]
@xags This used to be a fix for (I believe) aac audio being selected and devices that didn't support it would have no sound. This was a work-around by @eracknaphobia to select the first in the list if I recall. If it is no longer needed or needs tweaked I can take a look.

**Comment by xags** [comment]
@d21spike Hmm, it seems like maybe a race condition to me where it takes a second to start the stream and receive the first audio segment and by the time that happens Kodi sets the stream to default/nothing. I'd certainly appreciate a look. Not having to maintain a separate fork is nice. :)

I can say that I've had it commented-out for 4-5 months without a single audio related issue but my 4 devices are all the same (Skull Canyon NUC w/LibreElec) so I guess it could break certain devices?

**Comment by d21spike** [comment]
@xags I look into it and yeah I agree on the extra work. As quick test I saw an immediate improvement on Starz Edge. I'll test more channels. If no issues, I'll push it soon.

**Comment by d21spike** [comment]
@xags Please try version 0.0.108 pushed with commit b70529e1f756bc78129fb410292283b40e836e38

**Comment by xags** [comment]
@d21spike I can validate that this fixes the issues. No other auth or audio issues present with the changes that I can tell. Thanks!
