### ISSUE TITLE
inputstream.adaptive is missing

### ISSUE THREAD

**Issue by JoeIsCool** [d21spike/plugin.video.sling#25]
I am using the Slingtv addon on Kodi on vertsion 18.8 Debian package version: 2:18.8+dfsg1-2 Media Center Kodi from Debian.
When I try to watch any ondemand show I get the message, "inputstream.adaptive is missing on your Kodi install. This add-on is required to play this content." I think the things it needs are probably in inputstreamhelper, but I could be wrong.

**Comment by d21spike** [comment]
InputStream Adaptive is a plugin hosted on the Kodi  repo. You can install it from there under "VideoPlayer InputStream". It is required to play any Sling content via this addon.
![image](https://user-images.githubusercontent.com/6399602/108638068-69c07a80-745b-11eb-9c16-3cd129b32e44.png)

**Comment by JoeIsCool** [comment]
"VideoPlayer InputStream" is not an addon category and searching for that term yields nothing. The closest category is "Video addons". It doesn't have it. Searching all addons for the word Inputstream only returns "InputStream Helper".

**Comment by xags** [comment]
@JoeIsCool The package isn't in the stable Debian branch but it is in testing:

https://packages.debian.org/testing/source/kodi-inputstream-adaptive

Deb-multimedia may also have it (under stable):

apt-cache policy kodi-inputstream-adaptive 
kodi-inputstream-adaptive:
  Installed: (none)
  Candidate: 2.4.6-dmo0+deb10u1
  Version table:
     2.4.6-dmo0+deb10u1 1
          1 http://www.deb-multimedia.org stable/main amd64 Packages

Make sure you know what you're doing when installing from either source as it can mess up a default Debian-based Kodi install..

**Comment by JoeIsCool** [comment]
It looks like using Debian Testing leads to "xbmc.python.version 2.26.0 could not be satisfied". Maybe if you use something other than Debian testing but still install that package, it will work.

**Comment by JoeIsCool** [comment]
Just so you know, this add-on does not work in Kodi 19. And since that is the current version, Kodi 18.9 has to be built from source. And getting the add-on from apt does not seem to add it to the source-built Kodi 18.9. So I think it is beyond your responsibility to fix this, unless you know off the top of your head where I can download inputstream-adaptive from.
