### ISSUE TITLE
Please add support for Kodi 18.

### ISSUE THREAD

**Issue by CHJ85** [d21spike/plugin.video.sling#37]
Hi there. Kodi 19 is still very new and addons do not work yet, and there are very few good builds for Kodi 19 yet.
Please consider making this addon work for Kodi 18.

**Comment by d21spike** [comment]
There already is a Leia version, change the branch and download.

![image](https://user-images.githubusercontent.com/6399602/129812452-884e7d52-56f6-456f-88e5-d0637e037d99.png)

**Comment by CHJ85** [comment]
Oh thank you. I had no idea.

**Comment by d21spike** [comment]
No problem.
