### ISSUE TITLE
status of Widevine CDM on aarch64

### ISSUE THREAD

**Issue by graysky2** [d21spike/plugin.video.sling#45]
Thanks for the addon.  Is there any development status of Widevine CDM on aarch64?  The error I got when trying this on RPi4 aarch64 seems like a dealbreaker:
```
<general>: [script.module.inputstreamhelper] Unsupported 64-bit userspace found. User needs 32-bit userspace on arm64
````

**Comment by d21spike** [comment]
@graysky2 the DRM for this addon is handled by [Inputstream.Adaptive](https://github.com/xbmc/inputstream.adaptive). As far as I'm aware RPi4 is supported, albeit I only have older versions to test.

Doing some digging looks like there is no 64-bit version of Widevine for the arm64 architecture. You can see this issue referenced here:
![image](https://user-images.githubusercontent.com/6399602/189667492-2785a972-c40a-442c-9dee-dc2a43b999de.png)
[Raspberry Pi OS 64-bit](https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/)

Looks like there are some third party versions floating around you can try but they seem to have performance issues. The most straightforward way seems to be a 32-bit version of the RPi OS or a 64-bit kernel with a 32-bit userland. On a side note, the lack of Widevine support will also affect other streaming services that require it such as Netflix.

**Comment by graysky2** [comment]
Thanks again for the addon and for sharing your knowledge about this.  I am on ArchARM, but both armv7h and aarch64 are offered.  Not sure about aarch64 with armv7h (32-bit?) user-land.  Will need to look into that.  I will close this since you answered my question.
