### ISSUE TITLE
no video only audio

### ISSUE THREAD

**Issue by clonesr1** [d21spike/plugin.video.sling#48]
Windows 10, using iptv simple along sling. A couple of weeks ago I started having trouble with not getting a video feed, only audio on sling.

I uninstalled sling and iptv simple and reinstalled but continue to have the same problem. (sometimes the video will play on the first channel i choose but in trying to change the channel i get the same problem)

I also use nexrpvr along with the iptv simple and I o not have any trouble with video

Also posted on kodi forum four days agao

**Comment by hagertyoh** [comment]
I think this has to do with Kodi 20. My XBox updated to Kodi 20 RC1 automatically and I started having the same issues. Hopefully it will be fixed at some point. I updated a raspberry rpi4 with Kodi 20 and had similar issues. So it seems to not be isolated to windows.

**Comment by d21spike** [comment]
@clonesr1 @hagertyoh I just ran several tests on multiple versions

Versions tried Kodi 18.4 Win10, Kodi 19.3 Android, Kodi 19.5 Win10, Kodi 20-RC2 Win10, Kodi 20-RC2 Android

Both versions played live and recordings. These were clean installs. One thing to try would be to uninstall Kodi completely and reinstall, in case the update corrupts something.

**Comment by hagertyoh** [comment]
@d21spike Thanks for reviewing.  I Was confused on the Xbox not working.  The Xbox will probably never work as there is a wider widevine issue. 
The issue was with dropouts was raspberry pi4.  I will do a clean install once kodi 20 is released and report if problems.

**Comment by hagertyoh** [comment]
I completed a clean install with the newly released Kodi 20 on my firestick.  This issue has not repeated itself.  I think the clean install was the key.

**Comment by clonesr1** [comment]
Same here, did a clean install and all is good. Thank you
