### ISSUE TITLE
Oauth Authentication and Captcha Challenges Implemented

### ISSUE THREAD

**Issue by xags** [d21spike/plugin.video.sling#50]
It looks like I am no longer able to login through this application. After a bit of troubleshooting it looks like the Oauth URL has changed to: https://ms.p.sling.com/sling-api/oauth-helper/alpha/authenticate

It also looks like the payload it's expected has also changed:

`{
    "username": "****REDACTED****",
    "password": "****REDACTED****",
    "clientId": "aem_agentless_idp_client",
    "siteKey": "xxxxxxxxxx-****REDACTED****",
    "responseToken": "P1_eyJ0eXAiOiJKV****REDACTED****",
    "flowName": "login"
}`

Adding the the JSON data to the authentication payload and modifying the URL does not work and a 401 response is returned. It looks like the responseToken may be part of a new JS captcha implementation (hCaptcha?) that may be blocking the login. The value is dynamic and changes on each login.

I've just started to troubleshoot and wondering if anyone is having the same problem or come up with a solution? If the responseToken is the problem and Sling is using hCaptcha, it appears that there a few libraries that can solve the JS captcha but didn't want to go down this route if I'm looking at the issue incorrectly.

Thanks for the many years of this great add-on!

**Comment by bds3151** [comment]
I am having a similar problem (can't access any Sling TV channels) on several of my pc's, however one of them is still working.

**Comment by hagertyoh** [comment]
I am having similar problems on my firestick install and raspberry pi install.  If you could find a fix, That would be great.

**Comment by xags** [comment]
Closing. After getting an hCaptcha solver implemented and working, it appears the original authentication URL still works, and isn't protected by hCaptcha. The problem is line 89 in channels.py:

#self.Poster = metadata['default_schedule_image']['url'] if 'default_schedule_image' in metadata else self.Poster

Commenting it out fixes the issue temporarily. I'll see if I can submit a PR to actually fix it rather than commenting it out.

**Comment by bds3151** [comment]
Works great - thanks so much. A small correction is that this line is in the channel.py not channels,py.

**Comment by hagertyoh** [comment]
Thanks.   for me the fix only allowed the free channels not the paid channels.  Are others seeing the same?

**Comment by bds3151** [comment]
I'm getting all the Sling channels I had before.

**Comment by hagertyoh** [comment]
I see they all came in. I think I just needed to give it time to download everything
