### ISSUE TITLE
error message on sling

### ISSUE THREAD

**Issue by clonesr1** [d21spike/plugin.video.sling#51]
I started getting an error last night, I deleted the app but reinstalled and keep getting an error. (it is stuck at "downloading channel info" and some channels  play and some do not. https://paste.kodi.tv/tiqahecopi

Also from Joesteez on forum.kodi.tv "Hi all, just checking to see if this addon is still working for anyone? It stopped working yesterday for me. My account is active and I am logged in correctly. Getting an error when clicking My Channels. I think the new Freestream service was just rolled out by SLING. Thinking this may be the culprit. Maybe an addon update is required to handle? Love this addon. Thanks so much for the help!"

And an update from Doctor Eggs "It appears something has changed on Sling's end. The URL for the channel list is no longer valid so I'm trying to figure out where it is now located so that the add-on can be updated." Followed up with instructions to get it working

**Comment by bds3151** [comment]
Comment out line 89 in channel.py.

**Comment by clonesr1** [comment]
I'm sorry I dont really understand your response

**Comment by bds3151** [comment]
Modify the file channel.py with a text editor adding a # sign at the start (comment out) on line 89. Channel.py can be found in the original Plugin.video.sling.zip add on file. Then delete the add on in Kodi and reinstall the modified add on file.

**Comment by d21spike** [comment]
@clonesr1 @bds3151 I'll take a look at this shortly.

**Comment by d21spike** [comment]
@clonesr1 @bds3151 Try this release and let me know if it resolves your issue.
[plugin.video.sling-2023.05.01.1.zip](https://github.com/d21spike/IOFault-Repo/raw/Matrix/addons/plugin.video.sling/plugin.video.sling-2023.05.01.1.zip)

**Comment by bds3151** [comment]
2023.05.01.1.zip works fine. Thx

**Comment by clonesr1** [comment]
The updated zip works good. Thank you much

**Comment by hagertyoh** [comment]
Thank you for the update.
