### ISSUE TITLE
support for Android

### ISSUE THREAD

**Issue by crak3rjack** [d21spike/plugin.video.sling#9]
Does install but it does not open in Android

**Comment by eracknaphobia** [comment]
Log file?

**Comment by d21spike** [comment]
I have this running on a Galaxy S10+ with Kodi 19 Alpha as well as a Chromebook with Kodi 18.5 from the Play Store.

As @eracknaphobia said, ensure Debugging is turned on in both Kodi and the add-on. Then try to get a log. Also, did you ever get a login prompt or it didn't make it that far at all? Lastly, verify that you have an active internet connection where using the add-on.
![image](https://user-images.githubusercontent.com/6399602/72736413-a55b8780-3b6b-11ea-8fba-83bffada24a3.png)

**Comment by crak3rjack** [comment]
I'm new don't know much but there's a log hope it's what you need, using v-0.0.80
https://pastebin.com/cY8HJufu

**Comment by eracknaphobia** [comment]
This is platform independent. Currently playback is broken, see #10
